# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mlhpdx.udpping
PackageVersion: 0.0.2
InstallerLocale: en-US
InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mlhpdx/udpping/releases/download/0.0.2/udpping-0.0.2-win-x64.msi
  InstallerSha256: A7D42A6486500B5A308DA71A0155716FEE4D100E6FD492EFED1192D92C125CD2
  ProductCode: '{FB7F8AD9-849E-477A-AA81-1A660F782198}'
- Architecture: arm64
  InstallerUrl: https://github.com/mlhpdx/udpping/releases/download/0.0.2/udpping-0.0.2-win-arm64.msi
  InstallerSha256: 1265F27224BD50295234EF5B4CC12D626E957B6A6A60CDD26C689E1E1EBA697E
  ProductCode: '{57D1E42A-C7A5-4054-A8F8-87E4B95FC75D}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
