# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: mlhpdx.udpping
PackageVersion: 0.0.2
PackageLocale: en-US
Publisher: mlhpdx
PublisherUrl: https://github.com/mlhpdx
PublisherSupportUrl: https://github.com/mlhpdx/udpping/issues
PackageName: udpping
PackageUrl: https://github.com/mlhpdx/udpping
License: MIT
ShortDescription: A `gping`-style latency grapher that probes over plain UDP echo (RFC 862) instead of ICMP.
Tags:
- availability
- cli
- graph
- latency
- ping
- terminal-based
- udp
ReleaseNotesUrl: https://github.com/mlhpdx/udpping/releases/tag/0.0.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/mlhpdx/udpping/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
